// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCG6ip8peZNFumy0mEMAk9oLKoAFKu4tM',
    appId: '1:876788407089:web:c314c8bc04374ffa18ee10',
    messagingSenderId: '876788407089',
    projectId: 'front-siv',
    authDomain: 'front-siv.firebaseapp.com',
    storageBucket: 'front-siv.firebasestorage.app',
    measurementId: 'G-FP0X8KR4D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzoQnl5ZIaHxNEvvL1aRIigt1ldHbmqU',
    appId: '1:876788407089:android:118a81b1e78e596718ee10',
    messagingSenderId: '876788407089',
    projectId: 'front-siv',
    storageBucket: 'front-siv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdy5MSh8mTteedb9PikAQX2t-WCGjKKs',
    appId: '1:876788407089:ios:ae0c2bf3e45a92a718ee10',
    messagingSenderId: '876788407089',
    projectId: 'front-siv',
    storageBucket: 'front-siv.firebasestorage.app',
    iosBundleId: 'com.example.sivFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdy5MSh8mTteedb9PikAQX2t-WCGjKKs',
    appId: '1:876788407089:ios:ae0c2bf3e45a92a718ee10',
    messagingSenderId: '876788407089',
    projectId: 'front-siv',
    storageBucket: 'front-siv.firebasestorage.app',
    iosBundleId: 'com.example.sivFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCG6ip8peZNFumy0mEMAk9oLKoAFKu4tM',
    appId: '1:876788407089:web:c73aa15cd5aa0ab318ee10',
    messagingSenderId: '876788407089',
    projectId: 'front-siv',
    authDomain: 'front-siv.firebaseapp.com',
    storageBucket: 'front-siv.firebasestorage.app',
    measurementId: 'G-1BFQ01J32J',
  );
}
