name: comercial
description: "Pacote com regras de negocio do comercial"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  financeiro:
    path: ../financeiro
  estoque:
    path: ../estoque
  pessoas:
    path: ../pessoas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
