// Mocks generated by Mockito 5.4.6 from annotations
// in pessoas/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pessoas/domain/models/pessoa.dart' as _i2;
import 'package:pessoas/domain/usecases/criar_pessoa.dart' as _i3;
import 'package:pessoas/domain/usecases/recuperar_pessoa.dart' as _i7;
import 'package:pessoas/domain/usecases/recuperar_pessoa_pelo_documento.dart'
    as _i5;
import 'package:pessoas/domain/usecases/recuperar_pessoas.dart' as _i6;
import 'package:pessoas/domain/usecases/salvar_pessoa.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePessoa_0 extends _i1.SmartFake implements _i2.Pessoa {
  _FakePessoa_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CriarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockCriarPessoa extends _i1.Mock implements _i3.CriarPessoa {
  MockCriarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pessoa> call({
    required bool? bloqueado,
    required String? contato,
    required String? documento,
    required bool? eCliente,
    required bool? eFornecedor,
    required bool? eFuncionario,
    required String? email,
    String? inscricaoEstadual,
    required String? nome,
    required _i2.TipoContato? tipoContato,
    required _i2.TipoPessoa? tipoPessoa,
    required String? uf,
    required DateTime? dataDeNascimento,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #bloqueado: bloqueado,
            #contato: contato,
            #documento: documento,
            #eCliente: eCliente,
            #eFornecedor: eFornecedor,
            #eFuncionario: eFuncionario,
            #email: email,
            #inscricaoEstadual: inscricaoEstadual,
            #nome: nome,
            #tipoContato: tipoContato,
            #tipoPessoa: tipoPessoa,
            #uf: uf,
            #dataDeNascimento: dataDeNascimento,
          },
        ),
        returnValue: _i4.Future<_i2.Pessoa>.value(_FakePessoa_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #bloqueado: bloqueado,
              #contato: contato,
              #documento: documento,
              #eCliente: eCliente,
              #eFornecedor: eFornecedor,
              #eFuncionario: eFuncionario,
              #email: email,
              #inscricaoEstadual: inscricaoEstadual,
              #nome: nome,
              #tipoContato: tipoContato,
              #tipoPessoa: tipoPessoa,
              #uf: uf,
              #dataDeNascimento: dataDeNascimento,
            },
          ),
        )),
      ) as _i4.Future<_i2.Pessoa>);
}

/// A class which mocks [RecuperarPessoaPeloDocumento].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoaPeloDocumento extends _i1.Mock
    implements _i5.RecuperarPessoaPeloDocumento {
  MockRecuperarPessoaPeloDocumento() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pessoa?> call({required String? documento}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#documento: documento},
        ),
        returnValue: _i4.Future<_i2.Pessoa?>.value(),
      ) as _i4.Future<_i2.Pessoa?>);
}

/// A class which mocks [RecuperarPessoas].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoas extends _i1.Mock implements _i6.RecuperarPessoas {
  MockRecuperarPessoas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Iterable<_i2.Pessoa>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<Iterable<_i2.Pessoa>>.value(<_i2.Pessoa>[]),
      ) as _i4.Future<Iterable<_i2.Pessoa>>);
}

/// A class which mocks [RecuperarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoa extends _i1.Mock implements _i7.RecuperarPessoa {
  MockRecuperarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pessoa?> call({required int? idPessoa}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#idPessoa: idPessoa},
        ),
        returnValue: _i4.Future<_i2.Pessoa?>.value(),
      ) as _i4.Future<_i2.Pessoa?>);
}

/// A class which mocks [SalvarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalvarPessoa extends _i1.Mock implements _i8.SalvarPessoa {
  MockSalvarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pessoa> call({
    required _i2.Pessoa? pessoa,
    String? nome,
    _i2.TipoPessoa? tipoPessoa,
    String? documento,
    String? uf,
    String? inscricaoEstadual,
    DateTime? dataDeNascimento,
    String? email,
    _i2.TipoContato? tipoContato,
    String? contato,
    bool? eCliente,
    bool? eFornecedor,
    bool? eFuncionario,
    bool? bloqueado,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #pessoa: pessoa,
            #nome: nome,
            #tipoPessoa: tipoPessoa,
            #documento: documento,
            #uf: uf,
            #inscricaoEstadual: inscricaoEstadual,
            #dataDeNascimento: dataDeNascimento,
            #email: email,
            #tipoContato: tipoContato,
            #contato: contato,
            #eCliente: eCliente,
            #eFornecedor: eFornecedor,
            #eFuncionario: eFuncionario,
            #bloqueado: bloqueado,
          },
        ),
        returnValue: _i4.Future<_i2.Pessoa>.value(_FakePessoa_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #pessoa: pessoa,
              #nome: nome,
              #tipoPessoa: tipoPessoa,
              #documento: documento,
              #uf: uf,
              #inscricaoEstadual: inscricaoEstadual,
              #dataDeNascimento: dataDeNascimento,
              #email: email,
              #tipoContato: tipoContato,
              #contato: contato,
              #eCliente: eCliente,
              #eFornecedor: eFornecedor,
              #eFuncionario: eFuncionario,
              #bloqueado: bloqueado,
            },
          ),
        )),
      ) as _i4.Future<_i2.Pessoa>);
}
