// Mocks generated by Mockito 5.4.6 from annotations
// in pessoas/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pessoas/domain/models/pessoa.dart' as _i2;
import 'package:pessoas/domain/usecases/cancelar_ponto.dart' as _i12;
import 'package:pessoas/domain/usecases/criar_pessoa.dart' as _i4;
import 'package:pessoas/domain/usecases/criar_pontos.dart' as _i11;
import 'package:pessoas/domain/usecases/recuperar_pessoa.dart' as _i8;
import 'package:pessoas/domain/usecases/recuperar_pessoa_pelo_documento.dart'
    as _i6;
import 'package:pessoas/domain/usecases/recuperar_pessoas.dart' as _i7;
import 'package:pessoas/domain/usecases/recuperar_pontos_da_pessoa.dart'
    as _i10;
import 'package:pessoas/domain/usecases/resgatar_pontos.dart' as _i13;
import 'package:pessoas/domain/usecases/salvar_pessoa.dart' as _i9;
import 'package:pessoas/models.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePessoa_0 extends _i1.SmartFake implements _i2.Pessoa {
  _FakePessoa_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePonto_1 extends _i1.SmartFake implements _i3.Ponto {
  _FakePonto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CriarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockCriarPessoa extends _i1.Mock implements _i4.CriarPessoa {
  MockCriarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Pessoa> call({
    required bool? bloqueado,
    required String? contato,
    required String? documento,
    required bool? eCliente,
    required bool? eFornecedor,
    required bool? eFuncionario,
    required String? email,
    String? inscricaoEstadual,
    required String? nome,
    required _i2.TipoContato? tipoContato,
    required _i2.TipoPessoa? tipoPessoa,
    required String? uf,
    required DateTime? dataDeNascimento,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #bloqueado: bloqueado,
            #contato: contato,
            #documento: documento,
            #eCliente: eCliente,
            #eFornecedor: eFornecedor,
            #eFuncionario: eFuncionario,
            #email: email,
            #inscricaoEstadual: inscricaoEstadual,
            #nome: nome,
            #tipoContato: tipoContato,
            #tipoPessoa: tipoPessoa,
            #uf: uf,
            #dataDeNascimento: dataDeNascimento,
          },
        ),
        returnValue: _i5.Future<_i2.Pessoa>.value(_FakePessoa_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #bloqueado: bloqueado,
              #contato: contato,
              #documento: documento,
              #eCliente: eCliente,
              #eFornecedor: eFornecedor,
              #eFuncionario: eFuncionario,
              #email: email,
              #inscricaoEstadual: inscricaoEstadual,
              #nome: nome,
              #tipoContato: tipoContato,
              #tipoPessoa: tipoPessoa,
              #uf: uf,
              #dataDeNascimento: dataDeNascimento,
            },
          ),
        )),
      ) as _i5.Future<_i2.Pessoa>);
}

/// A class which mocks [RecuperarPessoaPeloDocumento].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoaPeloDocumento extends _i1.Mock
    implements _i6.RecuperarPessoaPeloDocumento {
  MockRecuperarPessoaPeloDocumento() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Pessoa?> call({required String? documento}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#documento: documento},
        ),
        returnValue: _i5.Future<_i2.Pessoa?>.value(),
      ) as _i5.Future<_i2.Pessoa?>);
}

/// A class which mocks [RecuperarPessoas].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoas extends _i1.Mock implements _i7.RecuperarPessoas {
  MockRecuperarPessoas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Iterable<_i2.Pessoa>> call({String? busca}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#busca: busca},
        ),
        returnValue: _i5.Future<Iterable<_i2.Pessoa>>.value(<_i2.Pessoa>[]),
      ) as _i5.Future<Iterable<_i2.Pessoa>>);
}

/// A class which mocks [RecuperarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPessoa extends _i1.Mock implements _i8.RecuperarPessoa {
  MockRecuperarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Pessoa?> call({required int? idPessoa}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#idPessoa: idPessoa},
        ),
        returnValue: _i5.Future<_i2.Pessoa?>.value(),
      ) as _i5.Future<_i2.Pessoa?>);
}

/// A class which mocks [SalvarPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalvarPessoa extends _i1.Mock implements _i9.SalvarPessoa {
  MockSalvarPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Pessoa> call({
    required _i2.Pessoa? pessoa,
    String? nome,
    _i2.TipoPessoa? tipoPessoa,
    String? documento,
    String? uf,
    String? inscricaoEstadual,
    DateTime? dataDeNascimento,
    String? email,
    _i2.TipoContato? tipoContato,
    String? contato,
    bool? eCliente,
    bool? eFornecedor,
    bool? eFuncionario,
    bool? bloqueado,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #pessoa: pessoa,
            #nome: nome,
            #tipoPessoa: tipoPessoa,
            #documento: documento,
            #uf: uf,
            #inscricaoEstadual: inscricaoEstadual,
            #dataDeNascimento: dataDeNascimento,
            #email: email,
            #tipoContato: tipoContato,
            #contato: contato,
            #eCliente: eCliente,
            #eFornecedor: eFornecedor,
            #eFuncionario: eFuncionario,
            #bloqueado: bloqueado,
          },
        ),
        returnValue: _i5.Future<_i2.Pessoa>.value(_FakePessoa_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #pessoa: pessoa,
              #nome: nome,
              #tipoPessoa: tipoPessoa,
              #documento: documento,
              #uf: uf,
              #inscricaoEstadual: inscricaoEstadual,
              #dataDeNascimento: dataDeNascimento,
              #email: email,
              #tipoContato: tipoContato,
              #contato: contato,
              #eCliente: eCliente,
              #eFornecedor: eFornecedor,
              #eFuncionario: eFuncionario,
              #bloqueado: bloqueado,
            },
          ),
        )),
      ) as _i5.Future<_i2.Pessoa>);
}

/// A class which mocks [RecuperarPontosDaPessoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPontosDaPessoa extends _i1.Mock
    implements _i10.RecuperarPontosDaPessoa {
  MockRecuperarPontosDaPessoa() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Ponto>> call({required int? idPessoa}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#idPessoa: idPessoa},
        ),
        returnValue: _i5.Future<List<_i3.Ponto>>.value(<_i3.Ponto>[]),
      ) as _i5.Future<List<_i3.Ponto>>);
}

/// A class which mocks [CriarPontos].
///
/// See the documentation for Mockito's code generation for more information.
class MockCriarPontos extends _i1.Mock implements _i11.CriarPontos {
  MockCriarPontos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Ponto> call({
    required int? idPessoa,
    required int? valor,
    required String? descricao,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #idPessoa: idPessoa,
            #valor: valor,
            #descricao: descricao,
          },
        ),
        returnValue: _i5.Future<_i3.Ponto>.value(_FakePonto_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #idPessoa: idPessoa,
              #valor: valor,
              #descricao: descricao,
            },
          ),
        )),
      ) as _i5.Future<_i3.Ponto>);
}

/// A class which mocks [CancelarPonto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelarPonto extends _i1.Mock implements _i12.CancelarPonto {
  MockCancelarPonto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required int? idPessoa,
    required int? idPonto,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #idPessoa: idPessoa,
            #idPonto: idPonto,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ResgatarPontos].
///
/// See the documentation for Mockito's code generation for more information.
class MockResgatarPontos extends _i1.Mock implements _i13.ResgatarPontos {
  MockResgatarPontos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required int? idPessoa,
    required int? valor,
    required String? descricao,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #idPessoa: idPessoa,
            #valor: valor,
            #descricao: descricao,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
