// Mocks generated by Mockito 5.4.6 from annotations
// in produtos/test/doubles/usecases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:produtos/domain/models/tamanho.dart' as _i2;
import 'package:produtos/domain/use_cases/atualizar_cor.dart' as _i14;
import 'package:produtos/domain/use_cases/atualizar_tamanho.dart' as _i9;
import 'package:produtos/domain/use_cases/criar_cor.dart' as _i12;
import 'package:produtos/domain/use_cases/criar_tamanho.dart' as _i7;
import 'package:produtos/domain/use_cases/desativar_cor.dart' as _i13;
import 'package:produtos/domain/use_cases/desativar_tamanho.dart' as _i8;
import 'package:produtos/domain/use_cases/recuperar_cor.dart' as _i10;
import 'package:produtos/domain/use_cases/recuperar_cores.dart' as _i11;
import 'package:produtos/domain/use_cases/recuperar_tamanho.dart' as _i4;
import 'package:produtos/domain/use_cases/recuperar_tamanhos.dart' as _i6;
import 'package:produtos/models.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTamanho_0 extends _i1.SmartFake implements _i2.Tamanho {
  _FakeTamanho_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCor_1 extends _i1.SmartFake implements _i3.Cor {
  _FakeCor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecuperarTamanho].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarTamanho extends _i1.Mock implements _i4.RecuperarTamanho {
  MockRecuperarTamanho() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Tamanho?> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i2.Tamanho?>.value(),
          )
          as _i5.Future<_i2.Tamanho?>);
}

/// A class which mocks [RecuperarTamanhos].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarTamanhos extends _i1.Mock implements _i6.RecuperarTamanhos {
  MockRecuperarTamanhos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Tamanho>> call({String? nome, bool? inativo}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#nome: nome, #inativo: inativo}),
            returnValue: _i5.Future<List<_i2.Tamanho>>.value(<_i2.Tamanho>[]),
          )
          as _i5.Future<List<_i2.Tamanho>>);
}

/// A class which mocks [CriarTamanho].
///
/// See the documentation for Mockito's code generation for more information.
class MockCriarTamanho extends _i1.Mock implements _i7.CriarTamanho {
  MockCriarTamanho() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Tamanho> call(String? nome) =>
      (super.noSuchMethod(
            Invocation.method(#call, [nome]),
            returnValue: _i5.Future<_i2.Tamanho>.value(
              _FakeTamanho_0(this, Invocation.method(#call, [nome])),
            ),
          )
          as _i5.Future<_i2.Tamanho>);
}

/// A class which mocks [DesativarTamanho].
///
/// See the documentation for Mockito's code generation for more information.
class MockDesativarTamanho extends _i1.Mock implements _i8.DesativarTamanho {
  MockDesativarTamanho() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AtualizarTamanho].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtualizarTamanho extends _i1.Mock implements _i9.AtualizarTamanho {
  MockAtualizarTamanho() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Tamanho> call(int? id, String? nome) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id, nome]),
            returnValue: _i5.Future<_i2.Tamanho>.value(
              _FakeTamanho_0(this, Invocation.method(#call, [id, nome])),
            ),
          )
          as _i5.Future<_i2.Tamanho>);
}

/// A class which mocks [RecuperarCor].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarCor extends _i1.Mock implements _i10.RecuperarCor {
  MockRecuperarCor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Cor?> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i3.Cor?>.value(),
          )
          as _i5.Future<_i3.Cor?>);
}

/// A class which mocks [RecuperarCores].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarCores extends _i1.Mock implements _i11.RecuperarCores {
  MockRecuperarCores() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Cor>> call({String? nome, bool? inativo}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#nome: nome, #inativo: inativo}),
            returnValue: _i5.Future<List<_i3.Cor>>.value(<_i3.Cor>[]),
          )
          as _i5.Future<List<_i3.Cor>>);
}

/// A class which mocks [CriarCor].
///
/// See the documentation for Mockito's code generation for more information.
class MockCriarCor extends _i1.Mock implements _i12.CriarCor {
  MockCriarCor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Cor> call(String? nome) =>
      (super.noSuchMethod(
            Invocation.method(#call, [nome]),
            returnValue: _i5.Future<_i3.Cor>.value(
              _FakeCor_1(this, Invocation.method(#call, [nome])),
            ),
          )
          as _i5.Future<_i3.Cor>);
}

/// A class which mocks [DesativarCor].
///
/// See the documentation for Mockito's code generation for more information.
class MockDesativarCor extends _i1.Mock implements _i13.DesativarCor {
  MockDesativarCor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AtualizarCor].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtualizarCor extends _i1.Mock implements _i14.AtualizarCor {
  MockAtualizarCor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> call(int? id, String? nome) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id, nome]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}
