// Mocks generated by Mockito 5.4.6 from annotations
// in siv_front/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:autenticacao/domain/data/repositories/i_empresas_repository.dart'
    as _i8;
import 'package:autenticacao/domain/data/repositories/i_licenciados_repository.dart'
    as _i4;
import 'package:autenticacao/domain/data/repositories/i_token_repository.dart'
    as _i2;
import 'package:autenticacao/domain/data/repositories/i_usuarios_repository.dart'
    as _i3;
import 'package:autenticacao/domain/models/token.dart' as _i12;
import 'package:autenticacao/domain/models/usuario.dart' as _i14;
import 'package:autenticacao/domain/usecases/limpar_credenciais_de_autenticacao.dart'
    as _i5;
import 'package:autenticacao/domain/usecases/recuperar_permissoes_do_usuario.dart'
    as _i16;
import 'package:autenticacao/models.dart' as _i15;
import 'package:autenticacao/uses_cases.dart' as _i11;
import 'package:core/bloc.dart' as _i24;
import 'package:core/local_data_sourcers/database_configs/i_hive_database_instance.dart'
    as _i7;
import 'package:core/local_data_sourcers/database_configs/i_local_database_instance.dart'
    as _i6;
import 'package:core/paginacao.dart' as _i17;
import 'package:core/paginacao/paginacao.dart' as _i19;
import 'package:core/sync.dart' as _i23;
import 'package:estoque/estoque.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:precos/models.dart' as _i22;
import 'package:precos/repositorios.dart' as _i9;
import 'package:precos/use_cases.dart' as _i21;
import 'package:produtos/domain/use_cases/sincronizar_codigos.dart' as _i18;
import 'package:siv_front/presentation/bloc/sync_data/sync_data_bloc.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeITokenRepository_0 extends _i1.SmartFake
    implements _i2.ITokenRepository {
  _FakeITokenRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIUsuariosRepository_1 extends _i1.SmartFake
    implements _i3.IUsuariosRepository {
  _FakeIUsuariosRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeILicenciadosRepository_2 extends _i1.SmartFake
    implements _i4.ILicenciadosRepository {
  _FakeILicenciadosRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLimparCredenciaisDeAutenticacao_3 extends _i1.SmartFake
    implements _i5.LimparCredenciaisDeAutenticacao {
  _FakeLimparCredenciaisDeAutenticacao_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeILocalDatabaseInstance_4 extends _i1.SmartFake
    implements _i6.ILocalDatabaseInstance {
  _FakeILocalDatabaseInstance_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIHiveDatabaseInstance_5 extends _i1.SmartFake
    implements _i7.IHiveDatabaseInstance {
  _FakeIHiveDatabaseInstance_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEmpresasRepository_6 extends _i1.SmartFake
    implements _i8.IEmpresasRepository {
  _FakeIEmpresasRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeITabelasDePrecoRepository_7 extends _i1.SmartFake
    implements _i9.ITabelasDePrecoRepository {
  _FakeITabelasDePrecoRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPrecosDeReferenciasRepository_8 extends _i1.SmartFake
    implements _i9.IPrecosDeReferenciasRepository {
  _FakeIPrecosDeReferenciasRepository_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSyncDataState_9 extends _i1.SmartFake implements _i10.SyncDataState {
  _FakeSyncDataState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OnAutenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnAutenticado extends _i1.Mock implements _i11.OnAutenticado {
  MockOnAutenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tokenRepository),
            returnValue: _FakeITokenRepository_0(
              this,
              Invocation.getter(#tokenRepository),
            ),
          )
          as _i2.ITokenRepository);

  @override
  set lastToken(_i12.Token? value) => super.noSuchMethod(
    Invocation.setter(#lastToken, value),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Stream<_i12.Token> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Stream<_i12.Token>.empty(),
          )
          as _i13.Stream<_i12.Token>);

  @override
  void onTokenPut(_i12.Token? token, _i13.EventSink<dynamic>? sink) =>
      super.noSuchMethod(
        Invocation.method(#onTokenPut, [token, sink]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OnDesautenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnDesautenticado extends _i1.Mock implements _i11.OnDesautenticado {
  MockOnDesautenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<Null> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Stream<Null>.empty(),
          )
          as _i13.Stream<Null>);
}

/// A class which mocks [EstaAutenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockEstaAutenticado extends _i1.Mock implements _i11.EstaAutenticado {
  MockEstaAutenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tokenRepository),
            returnValue: _FakeITokenRepository_0(
              this,
              Invocation.getter(#tokenRepository),
            ),
          )
          as _i2.ITokenRepository);

  @override
  _i13.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [Deslogar].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeslogar extends _i1.Mock implements _i11.Deslogar {
  MockDeslogar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tokenRepository),
            returnValue: _FakeITokenRepository_0(
              this,
              Invocation.getter(#tokenRepository),
            ),
          )
          as _i2.ITokenRepository);

  @override
  _i3.IUsuariosRepository get usuariosRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuariosRepository),
            returnValue: _FakeIUsuariosRepository_1(
              this,
              Invocation.getter(#usuariosRepository),
            ),
          )
          as _i3.IUsuariosRepository);

  @override
  _i4.ILicenciadosRepository get licenciadosRepository =>
      (super.noSuchMethod(
            Invocation.getter(#licenciadosRepository),
            returnValue: _FakeILicenciadosRepository_2(
              this,
              Invocation.getter(#licenciadosRepository),
            ),
          )
          as _i4.ILicenciadosRepository);

  @override
  _i5.LimparCredenciaisDeAutenticacao get limparCredenciaisDeAutenticacao =>
      (super.noSuchMethod(
            Invocation.getter(#limparCredenciaisDeAutenticacao),
            returnValue: _FakeLimparCredenciaisDeAutenticacao_3(
              this,
              Invocation.getter(#limparCredenciaisDeAutenticacao),
            ),
          )
          as _i5.LimparCredenciaisDeAutenticacao);

  @override
  _i6.ILocalDatabaseInstance get localDatabaseInstance =>
      (super.noSuchMethod(
            Invocation.getter(#localDatabaseInstance),
            returnValue: _FakeILocalDatabaseInstance_4(
              this,
              Invocation.getter(#localDatabaseInstance),
            ),
          )
          as _i6.ILocalDatabaseInstance);

  @override
  _i7.IHiveDatabaseInstance get hiveDatabaseInstance =>
      (super.noSuchMethod(
            Invocation.getter(#hiveDatabaseInstance),
            returnValue: _FakeIHiveDatabaseInstance_5(
              this,
              Invocation.getter(#hiveDatabaseInstance),
            ),
          )
          as _i7.IHiveDatabaseInstance);

  @override
  _i13.Future<void> call({bool? apagarDadosLocais = true}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #apagarDadosLocais: apagarDadosLocais,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [RecuperarUsuarioDaSessao].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarUsuarioDaSessao extends _i1.Mock
    implements _i11.RecuperarUsuarioDaSessao {
  MockRecuperarUsuarioDaSessao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IUsuariosRepository get usuariosRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuariosRepository),
            returnValue: _FakeIUsuariosRepository_1(
              this,
              Invocation.getter(#usuariosRepository),
            ),
          )
          as _i3.IUsuariosRepository);

  @override
  _i13.Future<_i14.Usuario?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i14.Usuario?>.value(),
          )
          as _i13.Future<_i14.Usuario?>);
}

/// A class which mocks [RecuperarEmpresaDaSessao].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarEmpresaDaSessao extends _i1.Mock
    implements _i11.RecuperarEmpresaDaSessao {
  MockRecuperarEmpresaDaSessao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.IEmpresasRepository get empresasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#empresasRepository),
            returnValue: _FakeIEmpresasRepository_6(
              this,
              Invocation.getter(#empresasRepository),
            ),
          )
          as _i8.IEmpresasRepository);

  @override
  _i13.Future<_i15.Empresa?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i15.Empresa?>.value(),
          )
          as _i13.Future<_i15.Empresa?>);
}

/// A class which mocks [SincronizarPermissoesDoUsuario].
///
/// See the documentation for Mockito's code generation for more information.
class MockSincronizarPermissoesDoUsuario extends _i1.Mock
    implements _i11.SincronizarPermissoesDoUsuario {
  MockSincronizarPermissoesDoUsuario() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<Iterable<_i15.PermissaoDoUsuario>> call({
    required int? idUsuario,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#idUsuario: idUsuario}),
            returnValue: _i13.Future<Iterable<_i15.PermissaoDoUsuario>>.value(
              <_i15.PermissaoDoUsuario>[],
            ),
          )
          as _i13.Future<Iterable<_i15.PermissaoDoUsuario>>);
}

/// A class which mocks [RecuperarPermissoesDoUsuarioLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPermissoesDoUsuarioLocal extends _i1.Mock
    implements _i11.RecuperarPermissoesDoUsuarioLocal {
  MockRecuperarPermissoesDoUsuarioLocal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<Iterable<_i15.PermissaoDoUsuario>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<Iterable<_i15.PermissaoDoUsuario>>.value(
              <_i15.PermissaoDoUsuario>[],
            ),
          )
          as _i13.Future<Iterable<_i15.PermissaoDoUsuario>>);
}

/// A class which mocks [RecuperarPermissoesDoUsuario].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarPermissoesDoUsuario extends _i1.Mock
    implements _i16.RecuperarPermissoesDoUsuario {
  MockRecuperarPermissoesDoUsuario() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<Iterable<_i15.PermissaoDoUsuario>> call(int? idUsuario) =>
      (super.noSuchMethod(
            Invocation.method(#call, [idUsuario]),
            returnValue: _i13.Future<Iterable<_i15.PermissaoDoUsuario>>.value(
              <_i15.PermissaoDoUsuario>[],
            ),
          )
          as _i13.Future<Iterable<_i15.PermissaoDoUsuario>>);
}

/// A class which mocks [LimparSincronizacaoIncremental].
///
/// See the documentation for Mockito's code generation for more information.
class MockLimparSincronizacaoIncremental extends _i1.Mock
    implements _i17.LimparSincronizacaoIncremental {
  MockLimparSincronizacaoIncremental() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [SincronizarCodigos].
///
/// See the documentation for Mockito's code generation for more information.
class MockSincronizarCodigos extends _i1.Mock
    implements _i18.SincronizarCodigos {
  MockSincronizarCodigos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<_i19.Paginacao<dynamic>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Stream<_i19.Paginacao<dynamic>>.empty(),
          )
          as _i13.Stream<_i19.Paginacao<dynamic>>);
}

/// A class which mocks [SincronizarEstoque].
///
/// See the documentation for Mockito's code generation for more information.
class MockSincronizarEstoque extends _i1.Mock
    implements _i20.SincronizarEstoque {
  MockSincronizarEstoque() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<_i19.Paginacao<dynamic>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Stream<_i19.Paginacao<dynamic>>.empty(),
          )
          as _i13.Stream<_i19.Paginacao<dynamic>>);
}

/// A class which mocks [SincronziarTabelasDePreco].
///
/// See the documentation for Mockito's code generation for more information.
class MockSincronziarTabelasDePreco extends _i1.Mock
    implements _i21.SincronziarTabelasDePreco {
  MockSincronziarTabelasDePreco() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ITabelasDePrecoRepository get tabelasDePrecoRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tabelasDePrecoRepository),
            returnValue: _FakeITabelasDePrecoRepository_7(
              this,
              Invocation.getter(#tabelasDePrecoRepository),
            ),
          )
          as _i9.ITabelasDePrecoRepository);

  @override
  _i13.Stream<_i19.Paginacao<_i22.TabelaDePreco>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i13.Stream<_i19.Paginacao<_i22.TabelaDePreco>>.empty(),
          )
          as _i13.Stream<_i19.Paginacao<_i22.TabelaDePreco>>);
}

/// A class which mocks [SincronizarPrecos].
///
/// See the documentation for Mockito's code generation for more information.
class MockSincronizarPrecos extends _i1.Mock implements _i21.SincronizarPrecos {
  MockSincronizarPrecos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.IPrecosDeReferenciasRepository get precosDeReferenciasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#precosDeReferenciasRepository),
            returnValue: _FakeIPrecosDeReferenciasRepository_8(
              this,
              Invocation.getter(#precosDeReferenciasRepository),
            ),
          )
          as _i9.IPrecosDeReferenciasRepository);

  @override
  _i13.Stream<_i19.Paginacao<_i22.PrecoDaReferencia>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i13.Stream<_i19.Paginacao<_i22.PrecoDaReferencia>>.empty(),
          )
          as _i13.Stream<_i19.Paginacao<_i22.PrecoDaReferencia>>);
}

/// A class which mocks [RecuperarTokenJwt].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarTokenJwt extends _i1.Mock implements _i11.RecuperarTokenJwt {
  MockRecuperarTokenJwt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tokenRepository),
            returnValue: _FakeITokenRepository_0(
              this,
              Invocation.getter(#tokenRepository),
            ),
          )
          as _i2.ITokenRepository);

  @override
  _i13.Future<String?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);
}

/// A class which mocks [SyncWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncWebSocketService extends _i1.Mock
    implements _i23.SyncWebSocketService {
  MockSyncWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<_i23.SyncMudancaEvent> get mudancas =>
      (super.noSuchMethod(
            Invocation.getter(#mudancas),
            returnValue: _i13.Stream<_i23.SyncMudancaEvent>.empty(),
          )
          as _i13.Stream<_i23.SyncMudancaEvent>);

  @override
  _i13.Stream<bool> get conectado =>
      (super.noSuchMethod(
            Invocation.getter(#conectado),
            returnValue: _i13.Stream<bool>.empty(),
          )
          as _i13.Stream<bool>);

  @override
  void connect({required String? token, required String? baseUrl}) =>
      super.noSuchMethod(
        Invocation.method(#connect, [], {#token: token, #baseUrl: baseUrl}),
        returnValueForMissingStub: null,
      );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SyncDataBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncDataBloc extends _i1.Mock implements _i10.SyncDataBloc {
  MockSyncDataBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.SyncDataState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSyncDataState_9(this, Invocation.getter(#state)),
          )
          as _i10.SyncDataState);

  @override
  _i13.Stream<_i10.SyncDataState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i13.Stream<_i10.SyncDataState>.empty(),
          )
          as _i13.Stream<_i10.SyncDataState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void add(_i10.SyncDataEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i10.SyncDataEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i10.SyncDataState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i10.SyncDataEvent>(
    _i24.EventHandler<E, _i10.SyncDataState>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i24.Transition<_i10.SyncDataEvent, _i10.SyncDataState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i10.SyncDataEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i24.Change<_i10.SyncDataState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
