// Mocks generated by Mockito 5.4.6 from annotations
// in siv_front/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:autenticacao/domain/data/repositories/i_licenciados_repository.dart'
    as _i4;
import 'package:autenticacao/domain/data/repositories/i_token_repository.dart'
    as _i2;
import 'package:autenticacao/domain/data/repositories/i_usuarios_repository.dart'
    as _i3;
import 'package:autenticacao/domain/models/token.dart' as _i7;
import 'package:autenticacao/domain/models/usuario.dart' as _i5;
import 'package:autenticacao/domain/usecases/deslogar.dart' as _i11;
import 'package:autenticacao/domain/usecases/esta_autenticado.dart' as _i10;
import 'package:autenticacao/domain/usecases/on_autenticado.dart' as _i6;
import 'package:autenticacao/domain/usecases/on_desautenticado.dart' as _i9;
import 'package:autenticacao/domain/usecases/recuperar_usuario_da_sessao.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeITokenRepository_0 extends _i1.SmartFake
    implements _i2.ITokenRepository {
  _FakeITokenRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUsuariosRepository_1 extends _i1.SmartFake
    implements _i3.IUsuariosRepository {
  _FakeIUsuariosRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeILicenciadosRepository_2 extends _i1.SmartFake
    implements _i4.ILicenciadosRepository {
  _FakeILicenciadosRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsuario_3 extends _i1.SmartFake implements _i5.Usuario {
  _FakeUsuario_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnAutenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnAutenticado extends _i1.Mock implements _i6.OnAutenticado {
  MockOnAutenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository => (super.noSuchMethod(
        Invocation.getter(#tokenRepository),
        returnValue: _FakeITokenRepository_0(
          this,
          Invocation.getter(#tokenRepository),
        ),
      ) as _i2.ITokenRepository);

  @override
  set lastToken(_i7.Token? _lastToken) => super.noSuchMethod(
        Invocation.setter(
          #lastToken,
          _lastToken,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Stream<_i7.Token> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Stream<_i7.Token>.empty(),
      ) as _i8.Stream<_i7.Token>);

  @override
  void onTokenPut(
    _i7.Token? token,
    _i8.EventSink<dynamic>? sink,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onTokenPut,
          [
            token,
            sink,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OnDesautenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnDesautenticado extends _i1.Mock implements _i9.OnDesautenticado {
  MockOnDesautenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<Null> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Stream<Null>.empty(),
      ) as _i8.Stream<Null>);
}

/// A class which mocks [EstaAutenticado].
///
/// See the documentation for Mockito's code generation for more information.
class MockEstaAutenticado extends _i1.Mock implements _i10.EstaAutenticado {
  MockEstaAutenticado() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository => (super.noSuchMethod(
        Invocation.getter(#tokenRepository),
        returnValue: _FakeITokenRepository_0(
          this,
          Invocation.getter(#tokenRepository),
        ),
      ) as _i2.ITokenRepository);

  @override
  _i8.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [Deslogar].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeslogar extends _i1.Mock implements _i11.Deslogar {
  MockDeslogar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITokenRepository get tokenRepository => (super.noSuchMethod(
        Invocation.getter(#tokenRepository),
        returnValue: _FakeITokenRepository_0(
          this,
          Invocation.getter(#tokenRepository),
        ),
      ) as _i2.ITokenRepository);

  @override
  _i3.IUsuariosRepository get usuariosRepository => (super.noSuchMethod(
        Invocation.getter(#usuariosRepository),
        returnValue: _FakeIUsuariosRepository_1(
          this,
          Invocation.getter(#usuariosRepository),
        ),
      ) as _i3.IUsuariosRepository);

  @override
  _i4.ILicenciadosRepository get licenciadosRepository => (super.noSuchMethod(
        Invocation.getter(#licenciadosRepository),
        returnValue: _FakeILicenciadosRepository_2(
          this,
          Invocation.getter(#licenciadosRepository),
        ),
      ) as _i4.ILicenciadosRepository);

  @override
  _i8.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [RecuperarUsuarioDaSessao].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecuperarUsuarioDaSessao extends _i1.Mock
    implements _i12.RecuperarUsuarioDaSessao {
  MockRecuperarUsuarioDaSessao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IUsuariosRepository get usuariosRepository => (super.noSuchMethod(
        Invocation.getter(#usuariosRepository),
        returnValue: _FakeIUsuariosRepository_1(
          this,
          Invocation.getter(#usuariosRepository),
        ),
      ) as _i3.IUsuariosRepository);

  @override
  _i8.Future<_i5.Usuario> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<_i5.Usuario>.value(_FakeUsuario_3(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i8.Future<_i5.Usuario>);
}
